// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace AirlineIS.Server.Models;

public partial class Airport
{
    [Key]
    public int Id { get; set; }

    [Column("IATACode")]
    [StringLength(3)]
    [Unicode(false)]
    public string Iatacode { get; set; }

    [StringLength(3)]
    public string LocalCode { get; set; }

    [Required]
    [StringLength(30)]
    public string Name { get; set; }

    [Required]
    [StringLength(30)]
    public string City { get; set; }

    [Required]
    [StringLength(30)]
    public string Country { get; set; }

    [InverseProperty("Destination")]
    [JsonIgnore]
    public virtual ICollection<Flight> FlightDestinations { get; set; } = new List<Flight>();

    [InverseProperty("Origin")]
    [JsonIgnore]
    public virtual ICollection<Flight> FlightOrigins { get; set; } = new List<Flight>();
}