// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace AirlineIS.Server.Models;

public partial class Invoice
{
    [Key]
    public int Id { get; set; }

    public int TicketId { get; set; }

    public bool IsPaid { get; set; }

    [ForeignKey("TicketId")]
    [InverseProperty("Invoices")]
    [JsonIgnore]
    public virtual Ticket Ticket { get; set; }
}