// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace AirlineIS.Server.Models;

public partial class Passenger
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(30)]
    public string SurName { get; set; }

    [Required]
    [StringLength(30)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(30)]
    public string LastName { get; set; }

    [Required]
    [StringLength(16)]
    public string Phone { get; set; }

    [Required]
    [StringLength(30)]
    public string Email { get; set; }

    public DateOnly BirthDate { get; set; }

    [InverseProperty("Passenger")]
    [JsonIgnore]
    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}