// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace AirlineIS.Server.Models;

public partial class Plane
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(20)]
    public string Name { get; set; }

    [InverseProperty("Plane")]
    [JsonIgnore]
    public virtual ICollection<Flight> Flights { get; set; } = new List<Flight>();

    [InverseProperty("Plane")]
    [JsonIgnore]
    public virtual ICollection<PlaneSeat> PlaneSeats { get; set; } = new List<PlaneSeat>();
}