// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace AirlineIS.Server.Models;

public partial class Ticket
{
    [Key]
    public int Id { get; set; }

    public int FlightId { get; set; }

    public int PlaneSeatId { get; set; }

    public int PassengerId { get; set; }

    [ForeignKey("FlightId")]
    [InverseProperty("Tickets")]
    [JsonIgnore]
    public virtual Flight Flight { get; set; }

    [InverseProperty("Ticket")]
    [JsonIgnore]
    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    [ForeignKey("PassengerId")]
    [InverseProperty("Tickets")]
    [JsonIgnore]
    public virtual Passenger Passenger { get; set; }

    [ForeignKey("PlaneSeatId")]
    [InverseProperty("Tickets")]
    [JsonIgnore]
    public virtual PlaneSeat PlaneSeat { get; set; }
}